In [1]:
import numpy as np

In [2]:
M = 1
n = 2
hidden_layers = [3, 4]
r = 5

In [3]:
layers = hidden_layers.copy()
layers.append(r)

In [4]:
theta = [np.random.rand(layers[0], n+1)] + [np.random.rand(layers[l], layers[l-1]+1) for l in range(1, len(layers))]
theta

[array([[0.66993046, 0.81237917, 0.32762549],
        [0.10622127, 0.54897836, 0.53277739],
        [0.99417665, 0.1303899 , 0.19191024]]),
 array([[0.64338019, 0.06104403, 0.67113185, 0.15961529],
        [0.7199103 , 0.78362802, 0.34816173, 0.65495194],
        [0.92492762, 0.02185292, 0.67188483, 0.49195034],
        [0.12195232, 0.25909034, 0.01533174, 0.46928863]]),
 array([[0.77208029, 0.80606968, 0.35876049, 0.2494233 , 0.62929748],
        [0.33433682, 0.44184054, 0.70562193, 0.11942334, 0.76917973],
        [0.85987746, 0.97256018, 0.84321174, 0.59473501, 0.05751535],
        [0.20367992, 0.56312586, 0.47530998, 0.7526102 , 0.87790075],
        [0.10480344, 0.82571653, 0.89567361, 0.43245752, 0.79358422]])]

In [5]:
theta[2][0, 3]

0.24942329872372193

In [6]:
def g(z):
    """
        sigmoid(z)
    """
    return 1/(1 + np.exp(-z))

In [43]:
x = np.random.rand(n)
y = np.array([0, 1, 0, 0, 0])
print(x, np.hstack((np.ones(1), x)), y)

[0.44481271 0.61612297] [1.         0.44481271 0.61612297] [0 1 0 0 0]


In [24]:
theta[0]

array([[0.66993046, 0.81237917, 0.32762549],
       [0.10622127, 0.54897836, 0.53277739],
       [0.99417665, 0.1303899 , 0.19191024]])

In [23]:
netj0 = np.dot(theta[0][0].T, np.hstack((np.ones(1), x)))
oj0 = g(np.array([netj0, netj0]))
oj0

array([0.73306272, 0.73306272])

In [76]:
o = [np.zeros(l) for l in layers]
deltas = [np.zeros(l) for l in layers]
print(layers, o, deltas)

[3, 4, 5] [array([0., 0., 0.]), array([0., 0., 0., 0.]), array([0., 0., 0., 0., 0.])] [array([0., 0., 0.]), array([0., 0., 0., 0.]), array([0., 0., 0., 0., 0.])]


In [77]:
def netj(theta_j, x_j):
    return np.dot(theta_j.T, x_j)

In [78]:
# forward propagation

for l in range(len(layers)):
    for j in range(layers[l]):
        print(l, j, theta[l][j])
        if l == 0:
            print(netj(theta[l][j], np.hstack((np.ones(1), x))))
            o[l][j] = g(netj(theta[l][j], np.hstack((np.ones(1), x))))
            print(o[l][j])
        else:
            o[l][j] = g(netj(theta[l][j], np.hstack((np.ones(1), o[l-1]))))

o

0 0 [0.66993046 0.81237917 0.32762549]
1.2331446250131672
0.7743684832384804
0 1 [0.10622127 0.54897836 0.53277739]
0.6786702067561584
0.6634418367360676
0 2 [0.99417665 0.1303899  0.19191024]
1.1704160440643483
0.7632202094139003
1 0 [0.64338019 0.06104403 0.67113185 0.15961529]
1 1 [0.7199103  0.78362802 0.34816173 0.65495194]
1 2 [0.92492762 0.02185292 0.67188483 0.49195034]
1 3 [0.12195232 0.25909034 0.01533174 0.46928863]
2 0 [0.77135072 0.8055044  0.35811692 0.24880255 0.6288136 ]
2 1 [0.33448152 0.44195265 0.70574957 0.11954646 0.7692757 ]
2 2 [0.85940946 0.97219757 0.84279891 0.59433681 0.05720495]
2 3 [0.20291725 0.56253493 0.47463722 0.75196129 0.87739491]
2 4 [0.10411941 0.82518654 0.89507022 0.43187552 0.79313054]


[array([0.77436848, 0.66344184, 0.76322021]),
 array([0.77863498, 0.88671178, 0.85359409, 0.66617289]),
 array([0.91272464, 0.87201712, 0.94829676, 0.90789165, 0.91962895])]

In [91]:
# back propagation

# output layer
output_layer = -1
delta = (y - o[output_layer]) * o[output_layer] * (1 - o[output_layer])
deltas[output_layer] = delta

print(delta)

j = 0
k = 0
J_theta_derivative = -delta[j] * np.hstack((np.ones(1), o[output_layer - 1]))
print(J_theta_derivative)

learning_rate = 0.01

# x_j = np.hstack((np.ones(1), o[output_layer - 1]))
# for j in range(layers[output_layer]):
#     J_theta_derivative = -delta[j] * x_j
#     print(j, theta[output_layer][j], theta[output_layer][j] - (learning_rate * J_theta_derivative))
#     theta[output_layer][j] = theta[output_layer][j] - (learning_rate * J_theta_derivative)


# hidden layers

for l in reversed(range(len(hidden_layers))):
    for j in range(hidden_layers[l]):
        print(l, j, list(range(layers[l+1])))
        deltas[l][j] = sum(deltas[l+1][dwn_nbr] * theta[l+1][dwn_nbr, j] * o[l][j] * (1 - o[l][j]) for dwn_nbr in range(layers[l+1]))

[-0.07270616  0.01428331 -0.04649501 -0.0759219  -0.0679712 ]
[0.07270616 0.05661156 0.06446941 0.06206155 0.04843487]
1 0 [0, 1, 2, 3, 4]
1 1 [0, 1, 2, 3, 4]
1 2 [0, 1, 2, 3, 4]
1 3 [0, 1, 2, 3, 4]
0 0 [0, 1, 2, 3]
0 1 [0, 1, 2, 3]
0 2 [0, 1, 2, 3]


In [92]:
deltas

[array([-0.00835354, -0.00547791, -0.00599095]),
 array([-0.01954332, -0.01968614, -0.0189578 , -0.02894432]),
 array([-0.07270616,  0.01428331, -0.04649501, -0.0759219 , -0.0679712 ])]

In [94]:
theta

[array([[0.66993046, 0.81237917, 0.32762549],
        [0.10622127, 0.54897836, 0.53277739],
        [0.99417665, 0.1303899 , 0.19191024]]),
 array([[0.64338019, 0.06104403, 0.67113185, 0.15961529],
        [0.7199103 , 0.78362802, 0.34816173, 0.65495194],
        [0.92492762, 0.02185292, 0.67188483, 0.49195034],
        [0.12195232, 0.25909034, 0.01533174, 0.46928863]]),
 array([[0.76989659, 0.80437217, 0.35682753, 0.24756132, 0.6278449 ],
        [0.33476718, 0.44217508, 0.70600288, 0.1197903 , 0.769466  ],
        [0.85847956, 0.97147352, 0.84197435, 0.59354306, 0.05658547],
        [0.20139882, 0.56135262, 0.4732908 , 0.75066516, 0.87638337],
        [0.10275998, 0.82412804, 0.8938648 , 0.43071512, 0.79222493]])]

In [96]:
# update theta

for l in range(len(layers)):
    print(l)
    if l == 0:
        x_j = np.hstack((np.ones(1), x))
    else:
        x_j = np.hstack((np.ones(1), o[l-1]))
    print(x_j)
    for j in range(layers[l]):
        J_theta_derivative = - deltas[l][j] * x_j
        theta[l][j] = theta[l][j] - (learning_rate * J_theta_derivative)

0
[1.         0.44481271 0.61612297]
1
[1.         0.77436848 0.66344184 0.76322021]
2
[1.         0.77863498 0.88671178 0.85359409 0.66617289]


In [97]:
theta

[array([[0.66984692, 0.81234201, 0.32757402],
        [0.10616649, 0.548954  , 0.53274364],
        [0.99411674, 0.13036326, 0.19187333]]),
 array([[0.64318476, 0.06089269, 0.67100219, 0.15946613],
        [0.71971344, 0.78347558, 0.34803112, 0.65480169],
        [0.92473804, 0.02170612, 0.67175905, 0.49180565],
        [0.12166288, 0.2588662 , 0.01513971, 0.46906772]]),
 array([[0.76916953, 0.80380606, 0.35618284, 0.24694071, 0.62736056],
        [0.33491002, 0.44228629, 0.70612953, 0.11991222, 0.76956115],
        [0.85801461, 0.97111149, 0.84156208, 0.59314618, 0.05627574],
        [0.2006396 , 0.56076147, 0.47261759, 0.75001709, 0.8758776 ],
        [0.10208027, 0.82359879, 0.89326209, 0.43013492, 0.79177212]])]